### ISSUE TITLE
Constantly on?

### ISSUE THREAD

**Issue by freekeys** [skorokithakis/gr8w8upd8m8#4]
Hello,

I'm looking to use a Wii board and this script to build a cat food dispenser. I have a bowl with a motorised lid and plan to put it on the wii board. Then when my skinny cat steps on the board her weight is measured and logged, and the bowl opens. If it's the fat cat then the weight is still logged but the bowl won't open (ridiculous project I know!)

Does the board have the potential to be permanently on and synced and take a reading whenever a cat steps on, even when no human is around to run the script?

Thanks!

**Comment by skorokithakis** [comment]
Haha, that's fantastic. I think the board *can* stay on, yes, although if it turns off you won't be able to turn it off again. Maybe you can solder some wires to the reset button so you can reset the board from your computer/raspberry/whatever, though.

**Comment by freekeys** [comment]
Thanks for the quick response! Okay I'll give it a go...

**Comment by freekeys** [comment]
Actually quick question, so do you press the reset button every time you go to take a weight?

**Comment by skorokithakis** [comment]
You can press the button at the front of the board to turn it on, if you manage to connect it with Bluetooth like that, but it's been breaking recently, so I always press resync, yes.
