### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by pliski** [skorokithakis/gr8w8upd8m8#5]
on Ubuntu 19.04 when I first tried to execute xwiibind.sh I got this error: 
```bash: ./xwiibind.sh: /bin/sh^M: bad interpreter: No such file or directory```

It's because the file was saved with Windows style line endings.

Fixed with : 
```sed -i -e 's/\r$//' ./xwiibind.sh```
as described here:
https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter

**Comment by skorokithakis** [comment]
Fixed, thanks!
