### ISSUE TITLE
Any way for this to work on Mac (OSX)

### ISSUE THREAD

**Issue by nishant-iyengar** [skorokithakis/gr8w8upd8m8#6]
Hi, I was wondering if I could run the terminal and python scripts on my mac without issue. One of the downloads is BlueZ, which only comes for Linux. Thank you, much appreciated!

**Comment by skorokithakis** [comment]
I'm afraid I have no idea, but I don't think so. I haven't managed to get it to pair under recent Linux versions either, unfortunately.
