### ISSUE TITLE
ACK to data write received

### ISSUE THREAD

**Issue by loongruige** [skorokithakis/gr8w8upd8m8#8]
After _a lot_ of editing to make it up-to-date, I'm facing an issue.

1 - I used 2to3 to fix most of the stuff
2 - I replaced `.encode()` & `.decode()` with `.str(x).hex()`
3 - I replaced intype's definition with `intype = int(str(data[1]).replace("\\x", ""))`

After doing that, I face a problem where it just logs `_ACK to data write received_`.
After some debugging, I found out that when I press the main button, instead of sending `\x32`, the board sends `\x48` instead.

Any help will be appreciated.

**Comment by skorokithakis** [comment]
Hmm, I'm afraid I haven't looked at this code in years, so I don't really remember. I'd appreciate any PRs, though.

**Comment by loongruige** [comment]
I kind of fixed it by updating intype:
```python
intype = hex(int(data[1]))
```
and then changing what the if statements check for:
```python
if intype == "0x20":
elif intype == "0x21":
elif intype == "0x32":
```

Now aside from the issue, I am trying to make this compatible and working for up to date python, hopefully I'll finish it today or tomorrow and hopefully create a pull request. Yet there is _a LOT_ of changes to do, so hopefully I can do it.

**Comment by skorokithakis** [comment]
OK, let me know, thanks!
